#This bis a basic workflow to get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows to run this worflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can sequentially or in parallel
jobs:
  #this workflos contains a single job called "build"
  build: 
    #the type of runner that the job will run on 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF}}
        run: git remode add space
